version: "3"

services:
  app:
    build: .
    command: go run server.go
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/yama-koo/zipcloud-example
  db:
    image: mysql:5.7.25
    environment:
      MYSQL_DATABASE: zipcloud
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - db-zipcloud:/var/lib/mysql
      - ./mysql:/usr/src
      - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db-zipcloud:
    driver: local
